#tap "homebrew/cask-fonts"
#tap "homebrew/bundle"
#tap "homebrew/cask"
#tap "homebrew/core"
#tap "homebrew/services"

brew "fd"
brew "fzf"
brew "neofetch"
brew "neovim"
brew "node"
brew "rbenv"
brew "ripgrep"
brew "tmux"
brew "yarn"
brew "zsh"

cask "1password"
cask "alfred"
cask "orbstack"
cask "arc"
cask "karabiner-elements"
cask "ghostty"
cask "ngrok"
cask "nikitabobko/tap/aerospace"
cask "raycast"
cask "slack"
cask "spotify"

# fonts
cask "font-fira-code-nerd-font"
